//aws_access_key = ""
//aws_secret_key = ""
myami = "ami-016eb5d644c333ccb"
mykey = "first-key"
tags = ["postgresql", "nodejs", "react"]
instancetype = "t2.micro"
num = 3
region = "us-east-1"
mysecgr = "project-208-sec-gr"
user = "okutan"