pipeline {
    agent any
    
    stages {
        stage('terraform infa create') {
            steps {
                sh 'cd solution_files && pwd'
                sh 'pwd && terraform init'
                sh 'terraform apply --auto-approve'
            }
        }
       
    }
}