pipeline {
    agent any
    
    stages {
        stage('terraform infa create') {
            steps {
                sh 'cd /var/lib/jenkins/workspace/proje/solution_files'
                sh 'terraform init'
                sh 'terraform apply --auto-approve'
            }
        }
       
    }
}
